// Descrições (pt-BR) das flags e ajustes de config do servidor (HeavenMS/Cosmic v83).
// Usado pelos tooltips da tela de Configuração. Chave = nome exato do config.
// Nem toda chave precisa estar aqui; quem não tiver descrição simplesmente não mostra balão.

export const CONFIG_DESCRIPTIONS: Record<string, string> = {
  /* ── Gameplay ── */
  USE_AUTOBAN: "Liga o sistema de banimento automático (detecta trapaças/hacks e pune sozinho).",
  USE_AUTOBAN_LOG: "Registra em log as detecções do autoban (sem necessariamente banir).",
  USE_BUFF_EVERLASTING: "Buffs não expiram ao trocar de mapa ou canal — duram a sessão inteira.",
  USE_BUFF_MOST_SIGNIFICANT: "Ao reaplicar buffs, mantém apenas o mais forte de cada tipo.",
  USE_CPQ: "Habilita o Carnival PQ (party quest de PvP em Henesys/Perion).",
  USE_ENABLE_DAILY_EXPEDITIONS: "Permite expedições (bosses grandes) com limite diário.",
  USE_ENABLE_SOLO_EXPEDITIONS: "Permite entrar em expedições sozinho, sem exigir party mínima.",
  USE_ENFORCE_HPMP_SWAP: "No AP reset, só deixa trocar HP↔MP (não converte HP/MP em atributos).",
  USE_FAMILY_SYSTEM: "Habilita o sistema de Família (senior/junior, reputação e recompensas).",
  USE_FIXED_RATIO_HPMP_UPDATE: "Atualiza HP/MP por proporção fixa em vez de valor absoluto.",
  USE_NPCS_SCRIPTABLE: "Permite NPCs controlados por script (interações e menus customizados).",
  USE_OLD_GMS_STYLED_PQ_NPCS: "Usa os NPCs de party quest no estilo antigo do GMS.",
  USE_PARTY_FOR_STARTERS: "Exige party para iniciantes em certas mecânicas iniciais.",
  USE_PERFECT_GM_SCROLL: "Pergaminhos usados por um GM sempre têm 100% de sucesso.",
  USE_PERFECT_PITCH: "Habilita o item Perfect Pitch (usado em receitas/mecânicas específicas).",
  USE_PERFECT_SCROLLING: "TODOS os pergaminhos passam a ter 100% de sucesso (scrolling perfeito).",
  USE_QUEST_RATE: "Aplica o multiplicador de Quest Rate (recompensas de quest multiplicadas).",
  USE_RANDOMIZE_HPMP_GAIN: "Ganho de HP/MP ao subir de nível vira aleatório dentro de uma faixa (em vez de fixo).",

  /* ── Economy ── */
  USE_ANNOUNCE_SHOPITEMSOLD: "Avisa o dono quando um item é vendido na sua loja de jogador.",
  USE_DUEY: "Habilita o Duey (correio de itens e mesos entre jogadores).",
  USE_ENFORCE_ADMIN_ACCOUNT: "Exige uma conta de admin dedicada para usar comandos de GM.",
  USE_ENFORCE_ITEM_SUGGESTION: "Ativa o sistema de 'item sugerido' (destaque de item da semana).",
  USE_ENFORCE_JOB_LEVEL_RANGE: "Impede usar/equipar itens fora da faixa de nível/job permitida.",
  USE_ENFORCE_JOB_SP_RANGE: "Valida os pontos de skill (SP) dentro do que o job permite.",
  USE_ENFORCE_MDOOR_POSITION: "Valida a posição das Mystic Doors (anti-abuso de teleporte).",
  USE_ENFORCE_MERCHANT_SAVE: "Salva o estado dos Hired Merchants (lojas automáticas) periodicamente.",
  USE_ENFORCE_MOB_LEVEL_RANGE: "Reduz/nega EXP quando o nível do jogador está muito acima ou abaixo do mob.",
  USE_ENFORCE_NOVICE_EXPRATE: "Aplica uma taxa de EXP específica para personagens iniciantes (novice).",
  USE_ENFORCE_UNMERCHABLE_CASH: "Impede vender itens de cash em lojas de jogador.",
  USE_ENFORCE_UNMERCHABLE_PET: "Impede colocar pets à venda em lojas de jogador.",
  USE_EQUIPMNT_LVLUP_CASH: "Permite que itens de cash também subam de nível (equip leveling).",
  USE_ERASE_PERMIT_ON_OPENSHOP: "Consome a permissão (permit) do jogador ao abrir uma loja.",
  USE_ERASE_UNTRADEABLE_DROP: "Ao dropar item intransferível, ele some (não fica no chão pra outros).",
  USE_JOINT_CASHSHOP_INVENTORY: "Inventário de cash compartilhado entre os personagens da conta.",
  USE_MTS: "Habilita o MTS (Maple Trading System, leilão/mercado entre jogadores).",

  /* ── Events & Server ── */
  USE_ENABLE_RECALL_EVENT: "Habilita o evento de 'recall' (chamada de volta ao evento).",
  USE_SERVER_AUTOASSIGNER: "Usa o auto-distribuidor de AP do servidor (distribui os pontos automaticamente pela build).",
  USE_STARTING_AP_4: "Personagens novos começam com 4 em cada atributo base.",
  USE_WHOLE_SERVER_RANKING: "O ranking considera o servidor inteiro (todos os mundos juntos).",

  /* ── Debug ── */
  USE_DEBUG: "Modo debug geral (logs extras no servidor).",
  USE_DEBUG_SHOW_INFO_EQPEXP: "Loga informações de EXP de equipamento (equip leveling).",
  USE_DEBUG_SHOW_PACKET: "Loga os pacotes ENVIADOS pelo servidor (muito verboso).",
  USE_DEBUG_SHOW_RCVD_MVLIFE: "Loga pacotes de movimento de mobs/NPCs recebidos.",
  USE_DEBUG_SHOW_RCVD_PACKET: "Loga os pacotes RECEBIDOS pelo servidor (muito verboso).",

  /* ── Other ── */
  USE_ADD_RATES_BY_LEVEL: "Aplica bônus de rate conforme o nível do jogador sobe.",
  USE_ADD_SLOTS_BY_LEVEL: "Concede slots de upgrade extras conforme o nível (equip leveling).",
  USE_ANNOUNCE_CHANGEJOB: "Anuncia no servidor quando alguém avança de job.",
  USE_ANNOUNCE_NX_COUPON_LOOT: "Anuncia quando alguém dropa um cupom NX.",
  USE_ANTI_IMMUNITY_CRASH: "Proteção contra crash causado por hack de imunidade (anti-cheat).",
  USE_AUTOAGGRO_NEARBY: "Mobs ficam agressivos automaticamente com jogadores próximos.",
  USE_AUTOASSIGN_SECONDARY_CAP: "No auto-assign de AP, respeita um teto para o atributo secundário.",
  USE_AUTOASSIGN_STARTERS_AP: "Distribui automaticamente o AP inicial dos personagens novos.",
  USE_AUTOHIDE_GM: "GMs entram invisíveis (hide) automaticamente ao logar.",
  USE_AUTOSAVE: "Salva os personagens automaticamente em intervalos regulares.",
  USE_CHAIR_EXTRAHEAL: "Cadeiras dão cura extra de HP/MP ao sentar.",
  USE_CHARACTER_ACCOUNT_CHECK: "Valida se o personagem realmente pertence à conta (anti-spoof).",
  USE_CLEAR_OUTDATED_COUPONS: "Remove cupons expirados automaticamente.",
  USE_COMPULSORY_AUTOPOT: "Torna o auto-pot (poção por tecla) sempre ativo/obrigatório.",
  USE_CUSTOM_KEYSET: "Usa o mapeamento de teclas (keyset) customizado padrão do servidor.",
  USE_DEADLY_DOJO: "Deixa o Mu Lung Dojo mais perigoso (dano aumentado).",
  USE_DISPLAY_NUMBERS_WITH_COMMA: "Exibe números com separador de milhar (ex: 1,000,000).",
  USE_ENABLE_CHAT_LOG: "Registra o chat dos jogadores em log.",
  USE_ENABLE_FULL_RESPAWN: "Respawna todos os mobs do mapa de uma vez (respawn cheio).",
  USE_ENHANCED_CHSCROLL: "Chaos Scroll melhorado (evita valores negativos / faixa maior).",
  USE_ENHANCED_CRAFTING: "Sistema de crafting/Maker melhorado.",
  USE_EQUIPMNT_LVLUP_POWER: "Itens que sobem de nível ganham mais poder (stats) por nível.",
  USE_EQUIPMNT_LVLUP_SLOTS: "Itens que sobem de nível podem ganhar slots de upgrade.",
  USE_EQUIPS_ON_AUTOPOT: "Considera itens equipados na lógica do auto-pot.",
  USE_ERASE_PET_ON_EXPIRATION: "Apaga o pet quando ele expira.",
  USE_EXP_GAIN_LOG: "Registra os ganhos de EXP em log.",
  USE_FAST_DOJO_UPGRADE: "Torna o progresso/upgrade no Dojo mais rápido.",
  USE_FAST_REUSE_HERO_WILL: "Reduz o cooldown do Hero's Will (skill que remove seduce/stun).",
  USE_FISHING_SYSTEM: "Habilita o sistema de pesca.",
  USE_FULL_ARAN_SKILLSET: "Concede o conjunto completo de skills do Aran.",
  USE_FULL_HOLY_SYMBOL: "Holy Symbol dá bônus de EXP total mesmo com poucos (ou nenhum) membros na party.",
  USE_GODLY_ITEMS: "Habilita os Godly Items: chance de um equip ganho vir com stats acima do normal.",
  USE_IP_VALIDATION: "Valida o IP nas conexões (anti multi-conta/spoof).",
  USE_ITEM_SORT: "Habilita o botão de ordenar o inventário.",
  USE_ITEM_SORT_BY_NAME: "Ordena os itens por nome (em vez de por ID).",
  USE_MAKER_FEE_HEURISTICS: "Calcula a taxa (fee) do Maker por heurística de valor.",
  USE_MAKER_PERMISSIVE_ATKUP: "Maker permite aumentar ataque de forma mais permissiva.",
  USE_MAP_OWNERSHIP_SYSTEM: "Sistema de 'dono do mapa' — quem está farmando tem prioridade de loot.",
  USE_MAXRANGE: "Valida o alcance máximo de ações (anti-cheat de distância).",
  USE_MAXRANGE_ECHO_OF_HERO: "Aplica a validação de alcance também no Echo of Hero.",
  USE_MULTIPLE_SAME_EQUIP_DROP: "Permite dropar vários equipamentos iguais de uma vez.",
  USE_REFRESH_RANK_MOVE: "Atualiza a movimentação (subida/descida) no ranking.",
  USE_SPAWN_CLEAN_MDOOR: "Limpa Mystic Doors ao spawnar (evita portas órfãs).",
  USE_SPAWN_RELEVANT_LOOT: "Só dropa loot considerado relevante para o jogador.",
  USE_STACK_COUPON_RATES: "Cupons de rate acumulam (empilham) com o rate base do servidor.",
  USE_STORAGE_ITEM_SORT: "Habilita ordenar os itens no armazém (storage).",
  USE_SUPPLY_RATE_COUPONS: "Fornece cupons de rate aos jogadores.",
  USE_ULTRA_NIMBLE_FEET: "Versão 'ultra' (bem mais forte) da skill Nimble Feet de iniciante.",
  USE_ULTRA_RECOVERY: "Versão 'ultra' (bem mais forte) da skill Recovery de iniciante.",
  USE_ULTRA_THREE_SNAILS: "Versão 'ultra' (bem mais forte) da skill Three Snails de iniciante.",
  USE_UNDISPEL_HOLY_SHIELD: "Holy Shield não pode ser dissipado (dispel) pelos mobs.",
  USE_UNITPRICE_WITH_COMMA: "Exibe o preço unitário com separador de milhar (vírgula).",

  /* ── Login ── */
  ENABLE_PIC: "Exige o PIC (código secundário de personagem) no login.",
  ENABLE_PIN: "Exige o PIN no login.",
  AUTOMATIC_REGISTER: "Cria a conta automaticamente no primeiro login (sem cadastro prévio).",

  /* ── Server Settings (numéricos) ── */
  BLOCK_NPC_RACE_CONDT: "Janela (ms) que bloqueia condição de corrida ao interagir com NPCs.",
  BONUS_HP_PER_LEVEL: "HP bônus concedido por nível.",
  BYPASS_PIC_EXPIRATION: "Tempo (min) em que o PIC fica dispensado após digitá-lo.",
  BYPASS_PIN_EXPIRATION: "Tempo (min) em que o PIN fica dispensado após digitá-lo.",
  CHAIR_EXTRA_HEAL_MAX_DELAY: "Intervalo máximo (s) entre curas extras da cadeira.",
  CHAIR_EXTRA_HEAL_MULTIPLIER: "Multiplicador da cura extra ao sentar em cadeira.",
  CHANGE_EMBLEM_COST: "Custo em mesos para trocar o emblema da guild.",
  CHANNEL_LOAD: "Capacidade máxima de jogadores por canal.",
  CHANNEL_LOCKS: "Número de locks internos por canal (concorrência).",
  CHANNEL_SIZE: "Quantidade de canais por mundo.",
  CHSCROLL_STAT_RANGE: "Amplitude (±) de stats que um Chaos Scroll pode dar.",
  CHSCROLL_STAT_RATE: "Multiplicador de stats do Chaos Scroll.",
  COUPON_INTERVAL: "Intervalo (ms) de atualização dos cupons de rate.",
  CREATE_GUILD_COST: "Custo em mesos para criar uma guild.",
  CREATE_GUILD_MIN_PARTNERS: "Mínimo de membros na party para criar uma guild.",
  DOJO_ENERGY_ATK: "Energia de ataque ganha no Dojo.",
  DOJO_ENERGY_DMG: "Energia por dano no Dojo.",
  EQUIP_EXP_RATE: "Multiplicador de EXP de equipamento (equip leveling).",
  EVENT_END_TIMESTAMP: "Timestamp de término de um evento agendado.",
  EVENT_LOBBY_DELAY: "Atraso (s) no lobby dos eventos antes de começar.",
  EVENT_MAX_GUILD_QUEUE: "Máximo de guilds na fila de um evento.",
  EXPAND_GUILD_BASE_COST: "Custo base para expandir a capacidade da guild.",
  EXPAND_GUILD_MAX_COST: "Custo máximo para expandir a guild.",
  EXPAND_GUILD_TIER_COST: "Custo por tier ao expandir a guild.",
  EXP_SPLIT_COMMON_MOD: "Peso da divisão de EXP para membros comuns da party.",
  EXP_SPLIT_LEECH_INTERVAL: "Faixa de nível permitida para 'leechar' EXP em party.",
  EXP_SPLIT_LEVEL_INTERVAL: "Faixa de nível para dividir EXP em party.",
  EXP_SPLIT_MVP_MOD: "Peso extra de EXP para o MVP (quem mais causou dano) da party.",
  FAMILY_MAX_GENERATIONS: "Máximo de gerações rastreadas na árvore de Família.",
  FAMILY_REP_PER_BOSS_KILL: "Reputação de família ganha por abate de boss.",
  FAMILY_REP_PER_KILL: "Reputação de família por abate comum.",
  FAMILY_REP_PER_LEVELUP: "Reputação de família ganha ao subir de nível.",
  GODLY_ITEM_CHANCE: "Chance de um equip ganho virar Godly = 1 em N (ex: 10 = 1/10).",
  GODLY_ITEM_MAX_BONUS: "Bônus máximo (+0 até N) somado a cada stat de um item Godly.",
  INIT_CONNECTION_POOL_TIMEOUT: "Timeout (s) para inicializar o pool de conexões do banco.",
  ITEM_EXPIRE_CHECK: "Intervalo (ms) de checagem de expiração de itens.",
  ITEM_EXPIRE_TIME: "Tempo (ms) até um item no chão expirar.",
  ITEM_LIMIT_ON_MAP: "Máximo de itens dropados no chão por mapa.",
  ITEM_MONITOR_TIME: "Intervalo (ms) do monitor de itens.",
  KITE_EXPIRE_TIME: "Tempo (ms) até uma 'kite' (placa de anúncio) expirar.",
  LOCK_MONITOR_TIME: "Intervalo (ms) do monitor de locks (detecção de travas).",
  LOGIN_ATTEMPT_DURATION: "Janela (s) para contar tentativas de login.",
  MAX_ACCOUNT_LOGIN_ATTEMPT: "Máximo de tentativas de login antes de bloquear.",
  MAX_ALLOWED_ACCOUNT_HWID: "Máximo de HWIDs (máquinas) permitidos por conta.",
  MAX_AP: "Teto de pontos por atributo (STR/DEX/INT/LUK).",
  MAX_EQUIPMNT_LVLUP_STAT_UP: "Ganho máximo de stat por nível no equip leveling.",
  MAX_EQUIPMNT_STAT: "Valor máximo que um stat de equipamento pode atingir.",
  MAX_EVENT_LEVELS: "Máximo de níveis de dificuldade em eventos.",
  MAX_MONITORED_BUFFSTATS: "Máximo de buff stats monitorados por vez.",
  MINIMUM_GM_LEVEL_TO_DROP: "Nível mínimo de GM para poder dropar itens.",
  MINIMUM_GM_LEVEL_TO_TRADE: "Nível mínimo de GM para poder trocar itens.",
  MOB_STATUS_AGGRO_INTERVAL: "Intervalo (ms) de reavaliação do aggro dos mobs.",
  MOB_STATUS_AGGRO_PERSISTENCE: "Persistência do aggro do mob no jogador.",
  MOB_STATUS_MONITOR_LIFE: "Vida útil do monitor de status dos mobs.",
  MOB_STATUS_MONITOR_PROC: "Intervalo de processamento do monitor de status dos mobs.",
  MOUNT_EXHAUST_COUNT: "Usos antes da montaria cansar/consumir fadiga.",
  NAME_CHANGE_COOLDOWN: "Cooldown (ms) entre trocas de nome.",
  PARTY_BONUS_EXP_RATE: "Bônus de EXP por estar em party.",
  PET_AUTOHP_RATIO: "Limiar de HP (%) para o pet usar auto-poção de HP.",
  PET_AUTOMP_RATIO: "Limiar de MP (%) para o pet usar auto-poção de MP.",
  PET_EXHAUST_COUNT: "Usos antes do pet cansar (fadiga).",
  PLAYERNPC_AREA_STEPS: "Passos/espaçamento na área dos Player NPCs (estátuas de ranking).",
  PLAYERNPC_AREA_X: "Largura da área dos Player NPCs.",
  PLAYERNPC_AREA_Y: "Altura da área dos Player NPCs.",
  PLAYERNPC_INITIAL_X: "Posição X inicial dos Player NPCs.",
  PLAYERNPC_INITIAL_Y: "Posição Y inicial dos Player NPCs.",
  PQ_BONUS_EXP_RATE: "Bônus de EXP em party quests.",
  PURGING_INTERVAL: "Intervalo (ms) da rotina de limpeza (purge) do servidor.",
  QUEST_POINT_PER_EVENT_CLEAR: "Pontos de quest por concluir um evento.",
  QUEST_POINT_PER_QUEST_COMPLETE: "Pontos de quest por completar uma quest.",
  QUEST_POINT_REPEATABLE_INTERVAL: "Intervalo entre quests repetíveis que dão pontos.",
  QUEST_POINT_REQUIREMENT: "Requisito de pontos de quest para certas recompensas.",
  RANKING_INTERVAL: "Intervalo (ms) de atualização do ranking.",
  RESPAWN_INTERVAL: "Intervalo (ms) de respawn dos mobs.",
  SCROLL_CHANCE_ROLLS: "Quantas rolagens de chance por uso de pergaminho (mais = mais chances).",
  TIMEOUT_DURATION: "Timeout geral (ms) de operações do servidor.",
  TOT_MOB_QUEST_REQUIREMENT: "Requisito total de mobs em quests de caça.",
  UPDATE_INTERVAL: "Intervalo (ms) do loop principal de atualização do servidor.",
  WEDDING_BLESS_EXP: "EXP concedido pela benção de casamento.",
  WEDDING_GIFT_LIMIT: "Limite de presentes de casamento.",
  WEDDING_RESERVATION_DELAY: "Atraso (dias) para reservar um casamento.",
  WEDDING_RESERVATION_INTERVAL: "Intervalo entre reservas de casamento.",
  WLDLIST_SIZE: "Tamanho da lista de mundos disponíveis.",
  WORLDS: "Número de mundos ativos no servidor.",
  WORLD_TRANSFER_COOLDOWN: "Cooldown (ms) entre transferências de mundo.",
};
